// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcokVDAKViw7meDbeTR3zybKdaF0JH1zM',
    appId: '1:404226858694:web:ea1225bd3080d0d2ac81c7',
    messagingSenderId: '404226858694',
    projectId: 'flutter-notes-app-8741b',
    authDomain: 'flutter-notes-app-8741b.firebaseapp.com',
    storageBucket: 'flutter-notes-app-8741b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8kY5XLRnEZYjYSOekWtMPbULiYYVbuBY',
    appId: '1:404226858694:android:a5125d437b756fe1ac81c7',
    messagingSenderId: '404226858694',
    projectId: 'flutter-notes-app-8741b',
    storageBucket: 'flutter-notes-app-8741b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxNbk4BW-2CW7rMrLXX3k4WaCiDp8RslQ',
    appId: '1:404226858694:ios:6c447e31e5b65954ac81c7',
    messagingSenderId: '404226858694',
    projectId: 'flutter-notes-app-8741b',
    storageBucket: 'flutter-notes-app-8741b.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotesAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxNbk4BW-2CW7rMrLXX3k4WaCiDp8RslQ',
    appId: '1:404226858694:ios:6c447e31e5b65954ac81c7',
    messagingSenderId: '404226858694',
    projectId: 'flutter-notes-app-8741b',
    storageBucket: 'flutter-notes-app-8741b.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotesAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcokVDAKViw7meDbeTR3zybKdaF0JH1zM',
    appId: '1:404226858694:web:58539dbbad5a022bac81c7',
    messagingSenderId: '404226858694',
    projectId: 'flutter-notes-app-8741b',
    authDomain: 'flutter-notes-app-8741b.firebaseapp.com',
    storageBucket: 'flutter-notes-app-8741b.firebasestorage.app',
  );
}
